/**
 * Column helpers shared by every table, so conventions (docs/04) are applied
 * by construction rather than by remembering them.
 */

import { sql } from 'drizzle-orm';
import { pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';

/**
 * Time-ordered UUID (UUIDv7), generated by a SQL function created in the
 * bootstrap migration. Ordering by id then approximates insertion order, which
 * keeps B-tree inserts local without the enumerability of a sequence (docs/04).
 *
 * The function is built on `gen_random_uuid()`, which is a Postgres built-in,
 * so no extension is required.
 */
export const UUID_V7_SQL = sql`uuid_v7()`;

export const primaryId = () => uuid('id').primaryKey().default(UUID_V7_SQL);

export const timestamps = {
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
};

/** Present only on entities whose history other records depend on (docs/04). */
export const softDelete = {
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
};

export const authorship = {
  createdBy: uuid('created_by'),
  updatedBy: uuid('updated_by'),
};

/** Enum columns are text + CHECK: adding a value is a constraint change, not a type migration. */
export const enumText = <T extends string>(name: string, _values: readonly T[]) =>
  text(name).$type<T>();

export { pgTable };
